In [1]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

y_true = [0, 1, 1, 0, 1]
y_pred = [0, 0, 1, 0, 1]

cm = confusion_matrix(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
mae = mean_absolute_error(y_true, y_pred)
#rmse = mean_squared_error(y_true, y_pred, squared=False)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
print("Confusion Matrix:\n", cm)
print("Precision:", prec)
print("Recall:", rec)
print("F1 Score:", f1)
print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)

Confusion Matrix:
 [[2 0]
 [1 2]]
Precision: 1.0
Recall: 0.6666666666666666
F1 Score: 0.8
Mean Absolute Error: 0.2
Root Mean Squared Error: 0.4472135954999579

Task 1

Fraud Detection

Performance metrics

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

y_true = [1]*85 + [0]*900 + [1]*5 + [0]*15
y_pred = [1]*85 + [0]*900 + [0]*5 + [1]*15

cm = confusion_matrix(y_true, y_pred)
acc = accuracy_score(y_true,y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true,y_pred)

print("Confusion matrix: ")
print(cm)

print("Accuracy: ",acc)
print("Precision_score: ",prec)
print("Recall: ",rec)
print("F1 score: ",f1)

Confusion matrix:
[[900  15]
 [  5  85]]
Accuracy:  0.9800995024875622
Precision_score:  0.85
Recall:  0.9444444444444444
F1 score:  0.8947368421052632

Task 2

Another metrics example

In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

y_true =  [1]*80 + [0]*90 + [1]*20 + [0]*10
y_pred = [1]*80 + [0]*90 + [0]*20 + [1]*10

cm = confusion_matrix(y_true,y_pred)
acc = accuracy_score(y_true,y_pred)
prec = precision_score(y_true,y_pred)
rec = recall_score(y_true,y_pred)
f1 = f1_score(y_true,y_pred)

print("Confusion matrix:")
print(cm)

print("Accuracy: ",acc)
print("Precision: ",prec)
print("Recall: ",rec)
print("F1 Score: ",f1)

Confusion matrix:
[[90 10]
 [20 80]]
Accuracy:  0.85
Precision:  0.8888888888888888
Recall:  0.8
F1 Score:  0.8421052631578947

Task 3

In [4]:
from sklearn.metrics import mean_squared_error
import math

y_true = [10,20,30,40]

pred_a  = [12,19,33,41]

pred_b = [11,20,29,40]

rmse_a = math.sqrt(mean_squared_error(y_true,pred_a))
rmse_b = math.sqrt(mean_squared_error(y_true,pred_b)) 

print("RMSE Model A: ",rmse_a)
print("RMSE Model B: ",rmse_b)

if rmse_a < rmse_b:
    print("Model A is better")
else:
    print("Model B is better")

RMSE Model A:  1.9364916731037085
RMSE Model B:  0.7071067811865476
Model B is better

ML workflow

In [5]:
import numpy as np
from sklearn.linear_model import LinearRegression
# 1. Prepare Data (X must be 2D)
X = np.array([[1], [2], [3], [4]]) 
y = np.array([2, 4, 6, 8])
# 2. Initialize the Model
model = LinearRegression()
# 3. Training (The .fit() method)
model.fit(X, y)
# 4. Prediction
predictions = model.predict([[5]]) # Predict for x=5
# 5. Evaluation
print(f"{10-predictions}")

[0.]

In [6]:
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
df.head()
df.info()
df.describe()

OSError: [Errno 22] Invalid argument: 'Titanic-Dataset.csv'

In [ ]:
df["Age"].fillna(df["Age"].median(),inplace=True)
df

C:\Users\BRAIN\AppData\Local\Temp\ipykernel_5700\1557397881.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)
df

C:\Users\BRAIN\AppData\Local\Temp\ipykernel_5700\350048953.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Drop columns not useful for prediction
df.drop(columns=['PassengerId','Name','Ticket','Cabin'], inplace=True)

In [ ]:
df["Sex"] = df["Sex"].apply(lambda x: 1 if x== "female" else 0)
df = pd.get_dummies(df, columns=["Embarked"])
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,0,22.0,1,0,7.2500,False,False,True
1,1,1,1,38.0,1,0,71.2833,True,False,False
2,1,3,1,26.0,0,0,7.9250,False,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,0,35.0,0,0,8.0500,False,False,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.0,0,0,13.0000,False,False,True
887,1,1,1,19.0,0,0,30.0000,False,False,True
888,0,3,1,28.0,1,2,23.4500,False,False,True
889,1,1,0,26.0,0,0,30.0000,True,False,False
890,0,3,0,32.0,0,0,7.7500,False,True,False

In [ ]:
X = df.drop(columns= ["Survived"])
y = df["Survived"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

models = {
    "LogisticRegression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(n_estimators = 100,max_depth=5)
    "SVM": SVC(Kernel="rbf")
    "KNN": KNeighborsClassifier(n_neighbors=5)
}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    acc =  modle.score(X_test_scaled, y_test)
    print(f"{name}: {acc:.3f}")

y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
new_passenger = new_passenger.reshape(1,-1)
prediction = model.predict(new_passenger)
print("Survived" if prediction==1 else "Did not survive")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3403968503.py, line 16)

In [ ]:
class SimpleNeuralNetwork:
    def __init__(self):
        self.w1, self.b1 = 0.8, 0.2 # Layer 1 parameters
        self.w2, self.b2 = 0.5, -0.1 # Layer 2 parameters
    def forward(self, x):
# Input ==-> Layer 1 ==-> DataX ==-> Layer 2 ==-> Output
        data_x = (x * self.w1) + self.b1
        output = (data_x * self.w2) + self.b2
        return output
# Usage
nn = SimpleNeuralNetwork()
output = nn.forward(2.0)

Linearclass

In [ ]:
class LinearLayer:
    def __init__(self,w,b):
        self.w = w
        self.b = b
    def forward(self,x):
        return (x * self.w) + self.b
linear = LinearLayer(2,3)
linear.forward(3)

9

In [ ]:
class ModularNeuralNetwork:
    def __init__(self, layer1,layer2):
        self.layer1 = layer1
        self.layer2 = layer2
    def forward(self,x):
        data_x = self.layer1.forward(x)
        output =self.layer2.forward(data_x)
        return output
layer_1_obj = LinearLayer(w=0.8,b=0.2)
layer_2_obj = LinearLayer(w = 0.5,b=-0.1)
mnn = ModularNeuralNetwork(layer_1_obj,layer_2_obj)
output = mnn.forward(2.0)

In [ ]:
import torch
import torch.nn as nn
class PyTorchNeuralNetwork(nn.module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=1, out_features=1)
        self.layer2 = nn.Linear(1,1)
    def forward(self,x):
        data_x = self.layer1(x)
        output = self.layer2(data_x)
        return output
nn_model = PyTorchNeuralNetwork()
input_tensor = torch.tensor([2.0])
print(nn_model(input_tensor))

ModuleNotFoundError: No module named 'torch'

In [ ]:
import torch
import torch.nn as nn
class CustomNN(nn.module):
    def __init__(self):
        super().__init__()
        self.hidden1 = nn.Linear(3,4)
        self.hidden2 = nn.Linear(4,4)
        self.outpull = nn.Linear(4,1)
    def forward(self,inputs):
        data1 = self.hidden1(inputs)
        data2 = self.hidden2(data1)
        output = self.outputL(data2)
        return output
nn_model = CustomNN()
input_tensor = torch.tensor([2.0,1.5,2.3])
output = nn_model(input_tensor)
output

AttributeError: module 'torch.nn' has no attribute 'module'