Sorting & Ranking

In [12]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Marks": [85,90,78,92,88,76,95,89]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1    Sara   23    Karachi     90
2   Ahmed   20     Lahore     78
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

df.sort_values() → Sort by column
Sort by Marks (ascending)

In [13]:
print(df.sort_values("Marks"))

     Name  Age       City  Marks
5    Hina   21     Lahore     76
2   Ahmed   20     Lahore     78
0     Ali   21     Lahore     85
4   Usman   24    Karachi     88
7  Ayesha   22    Karachi     89
1    Sara   23    Karachi     90
3    Zara   22  Islamabad     92
6   Bilal   23  Islamabad     95

In [14]:
# sort values by name index
print(df.sort_values("Name"))

     Name  Age       City  Marks
2   Ahmed   20     Lahore     78
0     Ali   21     Lahore     85
7  Ayesha   22    Karachi     89
6   Bilal   23  Islamabad     95
5    Hina   21     Lahore     76
1    Sara   23    Karachi     90
4   Usman   24    Karachi     88
3    Zara   22  Islamabad     92

In [15]:
# sort by marks descending
print(df.sort_values("Marks",ascending=False))

     Name  Age       City  Marks
6   Bilal   23  Islamabad     95
3    Zara   22  Islamabad     92
1    Sara   23    Karachi     90
7  Ayesha   22    Karachi     89
4   Usman   24    Karachi     88
0     Ali   21     Lahore     85
2   Ahmed   20     Lahore     78
5    Hina   21     Lahore     76

In [16]:
# sort by multiple column
print(df.sort_values(["Age","Marks"]))

     Name  Age       City  Marks
2   Ahmed   20     Lahore     78
5    Hina   21     Lahore     76
0     Ali   21     Lahore     85
7  Ayesha   22    Karachi     89
3    Zara   22  Islamabad     92
1    Sara   23    Karachi     90
6   Bilal   23  Islamabad     95
4   Usman   24    Karachi     88

df.sort_index() → Sort by row index

In [17]:
# reverse index order
print(df.sort_index(ascending=False))

     Name  Age       City  Marks
7  Ayesha   22    Karachi     89
6   Bilal   23  Islamabad     95
5    Hina   21     Lahore     76
4   Usman   24    Karachi     88
3    Zara   22  Islamabad     92
2   Ahmed   20     Lahore     78
1    Sara   23    Karachi     90
0     Ali   21     Lahore     85

df.rank() → Ranking values

Creates ranking numbers

In [18]:
# rank marks
df["Rank"] = df["Marks"].rank()
df

     Name  Age       City  Marks  Rank
0     Ali   21     Lahore     85   3.0
1    Sara   23    Karachi     90   6.0
2   Ahmed   20     Lahore     78   2.0
3    Zara   22  Islamabad     92   7.0
4   Usman   24    Karachi     88   4.0
5    Hina   21     Lahore     76   1.0
6   Bilal   23  Islamabad     95   8.0
7  Ayesha   22    Karachi     89   5.0

In [19]:
# highest rank marks equal to 1
df["Rank"] = df["Marks"].rank(ascending=False)
df

     Name  Age       City  Marks  Rank
0     Ali   21     Lahore     85   6.0
1    Sara   23    Karachi     90   3.0
2   Ahmed   20     Lahore     78   7.0
3    Zara   22  Islamabad     92   2.0
4   Usman   24    Karachi     88   5.0
5    Hina   21     Lahore     76   8.0
6   Bilal   23  Islamabad     95   1.0
7  Ayesha   22    Karachi     89   4.0

df.nlargest() → Top values
Top 3 students by Marks

In [20]:
print(df.nlargest(3,"Marks"))

    Name  Age       City  Marks  Rank
6  Bilal   23  Islamabad     95   1.0
3   Zara   22  Islamabad     92   2.0
1   Sara   23    Karachi     90   3.0

df.nsmallest() → Lowest values
Lowest 3 Marks

In [21]:
print(df.nsmallest(3,"Marks"))

    Name  Age    City  Marks  Rank
5   Hina   21  Lahore     76   8.0
2  Ahmed   20  Lahore     78   7.0
0    Ali   21  Lahore     85   6.0

In [23]:
# A function to categorize sensor readings
def evaluate_voltage(v):
    if v > 14.0:
        return "High"
    elif v < 11.0:
        return "Low"
    else:
        return "Normal"

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Voltage": [10.5, 12.0, 15.2, 9.8, 13.5]
})

df["Status"] = df["Voltage"].apply(evaluate_voltage)
print(df)

   Voltage  Status
0     10.5     Low
1     12.0  Normal
2     15.2    High
3      9.8     Low
4     13.5  Normal

In [26]:
df[["Voltage","Status"]].head()

   Voltage  Status
0     10.5     Low
1     12.0  Normal
2     15.2    High
3      9.8     Low
4     13.5  Normal

Aggregation & statistics method

Cretae data set

In [2]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "Marks": [85,90,78,92,88,76,95,89]
}

df = pd.DataFrame(data)
print(df)

     Name  Age  Marks
0     Ali   21     85
1    Sara   23     90
2   Ahmed   20     78
3    Zara   22     92
4   Usman   24     88
5    Hina   21     76
6   Bilal   23     95
7  Ayesha   22     89

In [ ]:
# count values
df.sum(numeric_only=True)

Age      176
Marks    693
dtype: int64

In [15]:
#Average values
df.mean(numeric_only=True)

Age      22.000
Marks    86.625
dtype: float64

In [ ]:
#Middle value
df.median(numeric_only=True)

Age      22.0
Marks    88.5
dtype: float64

In [ ]:
# most frequent variable
df.mode()

     Name   Age  Marks
0   Ahmed  21.0     76
1     Ali  22.0     78
2  Ayesha  23.0     85
3   Bilal   NaN     88
4    Hina   NaN     89
5    Sara   NaN     90
6   Usman   NaN     92
7    Zara   NaN     95

In [27]:
df.min(numeric_only=True)

Age      20
Marks    76
dtype: int64

In [17]:
df.max(numeric_only=True)

Age      24
Marks    95
dtype: int64

Spread / Variation

In [ ]:
#standard deviation
df.std(numeric_only=True)

Age      1.309307
Marks    6.631903
dtype: float64

In [ ]:
# variance
df.var(numeric_only=True)

Age       1.714286
Marks    43.982143
dtype: float64

Position of MIN/Max

In [ ]:
#row index of min valu
df.idxmin(numeric_only=True)

Age      2
Marks    5
dtype: int64

In [ ]:
# row index of max value
df.idxmax(numeric_only=True)

Age      4
Marks    6
dtype: int64

Relationship Between Columns

In [ ]:
#show relationship between columns
df.corr(numeric_only=True)

            Age     Marks
Age    1.000000  0.723894
Marks  0.723894  1.000000

In [ ]:
#covariance
df.cov(numeric_only=True)

            Age      Marks
Age    1.714286   6.285714
Marks  6.285714  43.982143

Percentiles

In [24]:
df.quantile(0.25, numeric_only=True)
df.quantile(0.50, numeric_only=True)
df.quantile(0.75, numeric_only=True)

Age      23.0
Marks    90.5
Name: 0.75, dtype: float64

Column Specific Aggregation

In [25]:
df["Marks"].mean()
df["Marks"].max()
df["Marks"].min()

76

GroupBy & Apply

In [1]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Department": ["IT","HR","IT","Finance","HR","IT","Finance","HR"],
    "Marks": [85,90,78,92,88,76,95,89],
    "Salary": [50000,60000,45000,65000,62000,48000,70000,61000]
}

df = pd.DataFrame(data)
print(df)

     Name       City Department  Marks  Salary
0     Ali     Lahore         IT     85   50000
1    Sara    Karachi         HR     90   60000
2   Ahmed     Lahore         IT     78   45000
3    Zara  Islamabad    Finance     92   65000
4   Usman    Karachi         HR     88   62000
5    Hina     Lahore         IT     76   48000
6   Bilal  Islamabad    Finance     95   70000
7  Ayesha    Karachi         HR     89   61000

In [2]:
df.groupby("City")["Marks"].mean()

City
Islamabad    93.500000
Karachi      89.000000
Lahore       79.666667
Name: Marks, dtype: float64

In [3]:
df.groupby("City")["Marks"].agg(["mean","max","min"])

                mean  max  min
City
Islamabad  93.500000   95   92
Karachi    89.000000   90   88
Lahore     79.666667   85   76

In [4]:
df.groupby(["City","Department"])["Salary"].mean()

City       Department
Islamabad  Finance       67500.000000
Karachi    HR            61000.000000
Lahore     IT            47666.666667
Name: Salary, dtype: float64

In [5]:
df.groupby("Department").mean(numeric_only=True)

                Marks        Salary
Department
Finance     93.500000  67500.000000
HR          89.000000  61000.000000
IT          79.666667  47666.666667

In [6]:
df.groupby("City").size()

City
Islamabad    2
Karachi      3
Lahore       3
dtype: int64

Or

In [7]:
df.groupby("City")["Name"].count()

City
Islamabad    2
Karachi      3
Lahore       3
Name: Name, dtype: int64

In [8]:
groups = df.groupby("City")

for city, data in groups:
    print("\nCity:",city)
    print(data)

City: Islamabad
    Name       City Department  Marks  Salary
3   Zara  Islamabad    Finance     92   65000
6  Bilal  Islamabad    Finance     95   70000

City: Karachi
     Name     City Department  Marks  Salary
1    Sara  Karachi         HR     90   60000
4   Usman  Karachi         HR     88   62000
7  Ayesha  Karachi         HR     89   61000

City: Lahore
    Name    City Department  Marks  Salary
0    Ali  Lahore         IT     85   50000
2  Ahmed  Lahore         IT     78   45000
5   Hina  Lahore         IT     76   48000

In [ ]:
def bonus(x):
    return x + 5000
df.groupby("Department")["Salary"].apply(bonus)

Department
Finance     3    70000
            6    75000
HR          1    65000
            4    67000
            7    66000
IT          0    55000
            2    50000
            5    53000
Name: Salary, dtype: int64

In [12]:
df["Salary"]

0    50000
1    60000
2    45000
3    65000
4    62000
5    48000
6    70000
7    61000
Name: Salary, dtype: int64

In [14]:
df["City_Avg_Marks"] = df.groupby("City")["Marks"].transform("mean")
df

     Name       City Department  Marks  Salary  City_Avg_Marks
0     Ali     Lahore         IT     85   50000       79.666667
1    Sara    Karachi         HR     90   60000       89.000000
2   Ahmed     Lahore         IT     78   45000       79.666667
3    Zara  Islamabad    Finance     92   65000       93.500000
4   Usman    Karachi         HR     88   62000       89.000000
5    Hina     Lahore         IT     76   48000       79.666667
6   Bilal  Islamabad    Finance     95   70000       93.500000
7  Ayesha    Karachi         HR     89   61000       89.000000

In [15]:
#Keep cities where avg marks > 85
df.groupby("City").filter(lambda x:  x["Marks"].mean() > 85)

     Name       City Department  Marks  Salary  City_Avg_Marks
1    Sara    Karachi         HR     90   60000            89.0
3    Zara  Islamabad    Finance     92   65000            93.5
4   Usman    Karachi         HR     88   62000            89.0
6   Bilal  Islamabad    Finance     95   70000            93.5
7  Ayesha    Karachi         HR     89   61000            89.0