Sorting & Ranking

In [12]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Marks": [85,90,78,92,88,76,95,89]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1    Sara   23    Karachi     90
2   Ahmed   20     Lahore     78
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

df.sort_values() → Sort by column
Sort by Marks (ascending)

In [13]:
print(df.sort_values("Marks"))

     Name  Age       City  Marks
5    Hina   21     Lahore     76
2   Ahmed   20     Lahore     78
0     Ali   21     Lahore     85
4   Usman   24    Karachi     88
7  Ayesha   22    Karachi     89
1    Sara   23    Karachi     90
3    Zara   22  Islamabad     92
6   Bilal   23  Islamabad     95

In [14]:
# sort values by name index
print(df.sort_values("Name"))

     Name  Age       City  Marks
2   Ahmed   20     Lahore     78
0     Ali   21     Lahore     85
7  Ayesha   22    Karachi     89
6   Bilal   23  Islamabad     95
5    Hina   21     Lahore     76
1    Sara   23    Karachi     90
4   Usman   24    Karachi     88
3    Zara   22  Islamabad     92

In [15]:
# sort by marks descending
print(df.sort_values("Marks",ascending=False))

     Name  Age       City  Marks
6   Bilal   23  Islamabad     95
3    Zara   22  Islamabad     92
1    Sara   23    Karachi     90
7  Ayesha   22    Karachi     89
4   Usman   24    Karachi     88
0     Ali   21     Lahore     85
2   Ahmed   20     Lahore     78
5    Hina   21     Lahore     76

In [16]:
# sort by multiple column
print(df.sort_values(["Age","Marks"]))

     Name  Age       City  Marks
2   Ahmed   20     Lahore     78
5    Hina   21     Lahore     76
0     Ali   21     Lahore     85
7  Ayesha   22    Karachi     89
3    Zara   22  Islamabad     92
1    Sara   23    Karachi     90
6   Bilal   23  Islamabad     95
4   Usman   24    Karachi     88

df.sort_index() → Sort by row index

In [17]:
# reverse index order
print(df.sort_index(ascending=False))

     Name  Age       City  Marks
7  Ayesha   22    Karachi     89
6   Bilal   23  Islamabad     95
5    Hina   21     Lahore     76
4   Usman   24    Karachi     88
3    Zara   22  Islamabad     92
2   Ahmed   20     Lahore     78
1    Sara   23    Karachi     90
0     Ali   21     Lahore     85

df.rank() → Ranking values

Creates ranking numbers

In [18]:
# rank marks
df["Rank"] = df["Marks"].rank()
df

     Name  Age       City  Marks  Rank
0     Ali   21     Lahore     85   3.0
1    Sara   23    Karachi     90   6.0
2   Ahmed   20     Lahore     78   2.0
3    Zara   22  Islamabad     92   7.0
4   Usman   24    Karachi     88   4.0
5    Hina   21     Lahore     76   1.0
6   Bilal   23  Islamabad     95   8.0
7  Ayesha   22    Karachi     89   5.0

In [19]:
# highest rank marks equal to 1
df["Rank"] = df["Marks"].rank(ascending=False)
df

     Name  Age       City  Marks  Rank
0     Ali   21     Lahore     85   6.0
1    Sara   23    Karachi     90   3.0
2   Ahmed   20     Lahore     78   7.0
3    Zara   22  Islamabad     92   2.0
4   Usman   24    Karachi     88   5.0
5    Hina   21     Lahore     76   8.0
6   Bilal   23  Islamabad     95   1.0
7  Ayesha   22    Karachi     89   4.0

df.nlargest() → Top values
Top 3 students by Marks

In [20]:
print(df.nlargest(3,"Marks"))

    Name  Age       City  Marks  Rank
6  Bilal   23  Islamabad     95   1.0
3   Zara   22  Islamabad     92   2.0
1   Sara   23    Karachi     90   3.0

df.nsmallest() → Lowest values
Lowest 3 Marks

In [21]:
print(df.nsmallest(3,"Marks"))

    Name  Age    City  Marks  Rank
5   Hina   21  Lahore     76   8.0
2  Ahmed   20  Lahore     78   7.0
0    Ali   21  Lahore     85   6.0

In [23]:
# A function to categorize sensor readings
def evaluate_voltage(v):
    if v > 14.0:
        return "High"
    elif v < 11.0:
        return "Low"
    else:
        return "Normal"

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Voltage": [10.5, 12.0, 15.2, 9.8, 13.5]
})

df["Status"] = df["Voltage"].apply(evaluate_voltage)
print(df)

   Voltage  Status
0     10.5     Low
1     12.0  Normal
2     15.2    High
3      9.8     Low
4     13.5  Normal

In [26]:
df[["Voltage","Status"]].head()

   Voltage  Status
0     10.5     Low
1     12.0  Normal
2     15.2    High
3      9.8     Low
4     13.5  Normal